name: Setup
description: Setup the Smile ID CI Environment
inputs:
  xcode:
    description: The version of Xcode to select
runs:
  using: composite
  steps:
  - name: Select Xcode ${{ inputs.xcode }}
    run: sudo xcode-select --switch /Applications/Xcode_${{ inputs.xcode }}.app
    if: ${{ inputs.xcode }}
    shell: bash

  - name: Install cocoapods
    run: sudo gem install cocoapods
    shell: bash
